name: Gatsby Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: git config --global user.email "tvq9612@gmail.com"
      - run: git config --global user.name "Quyen"
      - run: yarn install --pure-lockfile
      - run: yarn deploy
